teams:
- name: StackOverКлоуны
  id: 1
- name: sigma aura
  id: 2
- name: RuRebyC
  id: 3
- name: RSC
  id: 4
- name: re_Ytor
  id: 5
- name: "null"
  id: 6
- name: n1shchuk1
  id: 7
- name: N0_captur3_flag?:_(
  id: 8
- name: kulikalex
  id: 9
- name: Hack-trickers
  id: 10